### ISSUE TITLE
Ngrev fails to parse the project

### ISSUE THREAD

**Issue by ipassynk** [mgechev/ngrev#17]
Here is a link to the project: https://github.com/ipassynk/angular-springboot-jwt

ngrev on mac version 0.0.9

Trying to use ngrev on Mac. The following exception is displayed:
```
julia-mac:angular-springboot-jwt$/Applications/ngrev.app/Contents/MacOS/ngrev 
{ name: 'production' }
Loading project: "/Users/juliapassynkova/angular2/code/angular-springboot-jwt/package.json"
/Users/juliapassynkova/angular2/code/angular-springboot-jwt/package.json
Error: Error encountered resolving symbol values statically. Could not resolve app/guards/auth-guard.service relative to /Users/juliapassynkova/angular2/code/angular-springboot-jwt/src/app/app-routing.module.ts.
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23849:54)
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23680:56)
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23857:85
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23948:38
    at Array.forEach (native)
    at mapStringMap (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23947:24)
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23857:28)
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23680:56)
    at simplifyInContext (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23862:24)
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23624:69
```

The project complies with AOT without problem:

```
julia-mac:angular-springboot-jwt$ng build --prod --aot
Hash: 4d86fd37fd5320274fcf                                                              
Time: 16897ms
chunk    {0} polyfills.5aae015f16e5b66f61e9.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.c31742351d49e328b5f3.bundle.js (main) 96.5 kB {3} [initial] [rendered]
chunk    {2} styles.b17b8c150ef19d5eb7a6.bundle.css (styles) 122 bytes {4} [initial] [rendered]
chunk    {3} vendor.3048f582ab3c6e829f9b.bundle.js (vendor) 1.39 MB [initial] [rendered]
chunk    {4} inline.dab39c4f3c13a4e0b67f.bundle.js (inline) 0 bytes [entry] [rendered]

```

**Comment by mgechev** [comment]
Thanks for reporting the issue and providing a sample repo! Tomorrow I'll see what's wrong.

**Comment by mgechev** [comment]
Just tried it. For me it works properly. Did you install the project's dependencies before loading it in ngrev? Also, you can try the current master (`git clone ... && cd ngrev && npm start && npm run build && npm start`), because there was a regression that I just fixed.

**Comment by ipassynk** [comment]
Thanks a lot. I found the issue. All my import paths were format "app/..." and the app works but ngrev complained. So I changed all imports

 from

```
import {UserService} from 'app/services/user.service';
```

to

```
import {UserService} from './services/user.service';
```

and it works now. Thanks a lot. I head your presentation this year on ng-conf and it was really the best presentation ever! I am writing a blog on Medium about Angular SpringBoot JWT integration and I wanted to include the Angular app diagram. For Java there are a lot of tools that already do this and now I can do for Angular as well. Thanks again!

For this small toy project i am ok to change the imports but for big projects it will be a problem.

**Comment by mgechev** [comment]
@ipassynk would you try the [0.0.10 release](https://github.com/mgechev/ngrev/releases/tag/0.0.10), install the dependencies in the project's directory and tell me if the issue is still reproducible?

I tried to reproduce the problem a couple of times but for me everything works as expected.

**Comment by ipassynk** [comment]
Still the issue if import are not relative. Changing one import in app.module.ts to:
```
 import {AppComponent} from 'app/app.component';
```

 makes ngrev fails with:

```
/Users/juliapassynkova/angular2/code/angular-springboot-jwt/package.json
Error: Error encountered resolving symbol values statically. Could not resolve app/app.component relative to /Users/juliapassynkova/angular2/code/angular-springboot-jwt/src/app/app.module.ts.
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23849:54)
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23680:56)
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23857:85
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23948:38
    at Array.forEach (native)
    at mapStringMap (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23947:24)
    at simplify (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23857:28)
    at simplifyInContext (/Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23862:24)
    at /Applications/ngrev.app/Contents/Resources/app.asar/node_modules/@angular/compiler/bundles/compiler.umd.js:23830:112
    at Array.map (native)
```

**Comment by mgechev** [comment]
For me it works with and without `./` prefix for relative paths. I'm not sure what the difference could be - ngrev uses `@angular/compiler@4.1.0` which is the same one used by the project (tried it with 4.0.0 and everything seems to work fine too).

Electron has the following dependencies:

```
{
  http_parser: '2.7.0',
  node: '7.4.0',
  v8: '5.6.326.50',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '53',
  openssl: '1.0.2j',
  electron: '1.6.3',
  chrome: '56.0.2924.87',
  'atom-shell': '1.6.3'
}
```

But in your case, they should be the exact same versions (I believe) since you're using the packaged provided in releases.

Unfortunately, these issues are hard to debug since they are related to the internal mapping of the `StaticSymbols` and depend on the compiler's internal state.

**Comment by ipassynk** [comment]
I will try to reproduce the issue on another Mac today and let you know. Thanks a lot for your help.
