### ISSUE TITLE
Cannot parse (AOT compliant) project due to problem with MatExpansionModule?

### ISSUE THREAD

**Issue by david-bulte** [mgechev/ngrev#44]
I get a "Cannot parse your project" error with a nonsensical error message: Error during parsing: {}.

When starting the project from source code, I get some more info in the console: 

```
Get symbols
{ Error: Can't resolve all parameters for MatExpansionPanel in C:/moapr-dev/webclients/moapr/node_modules/@angular/material/expansion/typings/expansion-panel.d.ts: (?, [object Object], [object Object], [object Object], ?).
    at syntaxError (C:\stuff\ngrev\ngrev\node_modules\@angular\compiler\bundles\compiler.umd.js:1098:21)
    at CompileMetadataResolver._getDependenciesMetadata (C:\stuff\ngrev\ngrev\node_modules\@angular\compiler\bundles\compiler.umd.js:11008:39)
    at CompileMetadataResolver._getTypeMetadata (C:\stuff\ngrev\ngrev\node_modules\@angular\compiler\bundles\compiler.umd.js:10901:30)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\stuff\ngrev\ngrev\node_modules\@angular\compiler\bundles\compiler.umd.js:10520:28)
    at DirectiveSymbol.getNonResolvedMetadata (C:\stuff\ngrev\ngrev\node_modules\ngast\ngast.bundle.js:2139:42)
    at DirectiveSymbol.getProviders (C:\stuff\ngrev\ngrev\node_modules\ngast\ngast.bundle.js:2338:25)
    at C:\stuff\ngrev\ngrev\node_modules\ngast\ngast.bundle.js:2558:15
    at Array.forEach (<anonymous>)
    at ProjectSymbols.getProviders (C:\stuff\ngrev\ngrev\node_modules\ngast\ngast.bundle.js:2557:30)
    at SymbolIndexImpl.getIndex (C:\stuff\ngrev\ngrev\app\parser.js:1233:17) ngSyntaxError: true }
Got message with topic get-symbols
Got symbols response

```

So maybe an error in angular material? But like I said, my project AOT-compiles. Also when I comment out my usages of MatExpansionModule the problem persists.

**Comment by mgechev** [comment]
Try 0.0.24. It should be up in a few minutes.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/ngrev/commit/ea0d1e59eb7231be6d8305b53b321ef6559e80cd.
